server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hdtndmayctrztp:3605fea1c2e33ec42e33d79e464424ad648ccab928c03f9ee77c62d28a2312f3@ec2-18-204-101-137.compute-1.amazonaws.com:5432/d6hfom6a6pisd9
    username: hdtndmayctrztp
    password: 3605fea1c2e33ec42e33d79e464424ad648ccab928c03f9ee77c62d28a2312f3
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none


application:
  description: Projeto criado para o Bootcamp DIO - Santander / Backend

